//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Договор.
    /// </summary>
    // *** Start programmer edit section *** (Договор CustomAttributes)

    // *** End programmer edit section *** (Договор CustomAttributes)
    [PublishName("Contract")]
    [ClassStorage("Contract")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговорE", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "СрокДействия as \'Срок действия\'",
            "Покупатель as \'Покупатель\'",
            "Покупатель.Наименование as \'Наименование\'",
            "Продавец as \'Продавец\'",
            "Продавец.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Покупатель.Наименование",
            "Продавец.Наименование"})]
    [MasterViewDefineAttribute("ДоговорE", "Покупатель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ДоговорE", "Продавец", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ДоговорL", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "СрокДействия as \'Срок действия\'",
            "Покупатель.Наименование as \'Наименование\'",
            "Продавец.Наименование as \'Наименование\'"})]
    public class Договор : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fДата;

        private string fНомер;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fСрокДействия;

        private DataLine.TestGen270624.Организация fПокупатель;

        private DataLine.TestGen270624.Организация fПродавец;

        // *** Start programmer edit section *** (Договор CustomMembers)

        // *** End programmer edit section *** (Договор CustomMembers)


        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Дата CustomAttributes)

        // *** End programmer edit section *** (Договор.Дата CustomAttributes)
        [PropertyStorage("Date")]
        [PublishName("Date")]
        [NotNull()]
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Дата Get start)

                // *** End programmer edit section *** (Договор.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Договор.Дата Get end)

                // *** End programmer edit section *** (Договор.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Дата Set start)

                // *** End programmer edit section *** (Договор.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Договор.Дата Set end)

                // *** End programmer edit section *** (Договор.Дата Set end)
            }
        }

        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Номер CustomAttributes)

        // *** End programmer edit section *** (Договор.Номер CustomAttributes)
        [PropertyStorage("Number")]
        [PublishName("Number")]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Номер Get start)

                // *** End programmer edit section *** (Договор.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Договор.Номер Get end)

                // *** End programmer edit section *** (Договор.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Номер Set start)

                // *** End programmer edit section *** (Договор.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Договор.Номер Set end)

                // *** End programmer edit section *** (Договор.Номер Set end)
            }
        }

        /// <summary>
        /// СрокДействия.
        /// </summary>
        // *** Start programmer edit section *** (Договор.СрокДействия CustomAttributes)

        // *** End programmer edit section *** (Договор.СрокДействия CustomAttributes)
        [PropertyStorage("ValidityPeriod")]
        [PublishName("ValidityPeriod")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime СрокДействия
        {
            get
            {
                // *** Start programmer edit section *** (Договор.СрокДействия Get start)

                // *** End programmer edit section *** (Договор.СрокДействия Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fСрокДействия;
                // *** Start programmer edit section *** (Договор.СрокДействия Get end)

                // *** End programmer edit section *** (Договор.СрокДействия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.СрокДействия Set start)

                // *** End programmer edit section *** (Договор.СрокДействия Set start)
                this.fСрокДействия = value;
                // *** Start programmer edit section *** (Договор.СрокДействия Set end)

                // *** End programmer edit section *** (Договор.СрокДействия Set end)
            }
        }

        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Покупатель CustomAttributes)

        // *** End programmer edit section *** (Договор.Покупатель CustomAttributes)
        [PropertyStorage(new string[] {
                "Buyer"})]
        [PublishName("Buyer")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Организация Покупатель
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Покупатель Get start)

                // *** End programmer edit section *** (Договор.Покупатель Get start)
                DataLine.TestGen270624.Организация result = this.fПокупатель;
                // *** Start programmer edit section *** (Договор.Покупатель Get end)

                // *** End programmer edit section *** (Договор.Покупатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Покупатель Set start)

                // *** End programmer edit section *** (Договор.Покупатель Set start)
                this.fПокупатель = value;
                // *** Start programmer edit section *** (Договор.Покупатель Set end)

                // *** End programmer edit section *** (Договор.Покупатель Set end)
            }
        }

        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Продавец CustomAttributes)

        // *** End programmer edit section *** (Договор.Продавец CustomAttributes)
        [PropertyStorage(new string[] {
                "Seller"})]
        [PublishName("Seller")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Организация Продавец
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Продавец Get start)

                // *** End programmer edit section *** (Договор.Продавец Get start)
                DataLine.TestGen270624.Организация result = this.fПродавец;
                // *** Start programmer edit section *** (Договор.Продавец Get end)

                // *** End programmer edit section *** (Договор.Продавец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Продавец Set start)

                // *** End programmer edit section *** (Договор.Продавец Set start)
                this.fПродавец = value;
                // *** Start programmer edit section *** (Договор.Продавец Set end)

                // *** End programmer edit section *** (Договор.Продавец Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ДоговорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорE", typeof(DataLine.TestGen270624.Договор));
                }
            }

            /// <summary>
            /// "ДоговорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорL", typeof(DataLine.TestGen270624.Договор));
                }
            }
        }
    }
}

