//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Назначение т о для модели.
    /// </summary>
    // *** Start programmer edit section *** (НазначениеТОДляМодели CustomAttributes)

    // *** End programmer edit section *** (НазначениеТОДляМодели CustomAttributes)
    [PublishName("PurposeOfTheMaintenanceModel")]
    [ClassStorage("PurposeOfTheMaintenanceModel")]
    [AutoAltered()]
    [Caption("Назначение ТО для модели")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НазначениеТОДляМоделиE", new string[] {
            "МодельОборудования as \'Модель оборудования\'",
            "МодельОборудования.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "МодельОборудования.Наименование"})]
    [MasterViewDefineAttribute("НазначениеТОДляМоделиE", "МодельОборудования", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class НазначениеТОДляМодели : ICSSoft.STORMNET.DataObject
    {

        private DataLine.TestGen270624.МодельОборудования fМодельОборудования;

        private DataLine.TestGen270624.ПрограммаТО fПрограммаТО;

        // *** Start programmer edit section *** (НазначениеТОДляМодели CustomMembers)

        // *** End programmer edit section *** (НазначениеТОДляМодели CustomMembers)


        /// <summary>
        /// Назначение т о для модели.
        /// </summary>
        // *** Start programmer edit section *** (НазначениеТОДляМодели.МодельОборудования CustomAttributes)

        // *** End programmer edit section *** (НазначениеТОДляМодели.МодельОборудования CustomAttributes)
        [PropertyStorage(new string[] {
                "EquipmentModel"})]
        [PublishName("EquipmentModel")]
        [NotNull()]
        public virtual DataLine.TestGen270624.МодельОборудования МодельОборудования
        {
            get
            {
                // *** Start programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Get start)

                // *** End programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Get start)
                DataLine.TestGen270624.МодельОборудования result = this.fМодельОборудования;
                // *** Start programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Get end)

                // *** End programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Set start)

                // *** End programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Set start)
                this.fМодельОборудования = value;
                // *** Start programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Set end)

                // *** End programmer edit section *** (НазначениеТОДляМодели.МодельОборудования Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку DataLine.TestGen270624.ПрограммаТО.
        /// </summary>
        // *** Start programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО CustomAttributes)

        // *** End programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО CustomAttributes)
        [Agregator()]
        [PublishName("MaintenanceProgram")]
        [NotNull()]
        [PropertyStorage(new string[] {
                "MaintenanceProgram"})]
        public virtual DataLine.TestGen270624.ПрограммаТО ПрограммаТО
        {
            get
            {
                // *** Start programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Get start)

                // *** End programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Get start)
                DataLine.TestGen270624.ПрограммаТО result = this.fПрограммаТО;
                // *** Start programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Get end)

                // *** End programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Set start)

                // *** End programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Set start)
                this.fПрограммаТО = value;
                // *** Start programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Set end)

                // *** End programmer edit section *** (НазначениеТОДляМодели.ПрограммаТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "НазначениеТОДляМоделиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НазначениеТОДляМоделиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НазначениеТОДляМоделиE", typeof(DataLine.TestGen270624.НазначениеТОДляМодели));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of НазначениеТОДляМодели.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfНазначениеТОДляМодели CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfНазначениеТОДляМодели CustomAttributes)
    public class DetailArrayOfНазначениеТОДляМодели : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели members)

        // *** End programmer edit section *** (DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type НазначениеТОДляМодели by index.
        /// </summary>
        /// <summary>
        /// Adds object with type НазначениеТОДляМодели.
        /// </summary>
        public DetailArrayOfНазначениеТОДляМодели(DataLine.TestGen270624.ПрограммаТО fПрограммаТО) : 
                base(typeof(НазначениеТОДляМодели), ((ICSSoft.STORMNET.DataObject)(fПрограммаТО)))
        {
        }

        public DataLine.TestGen270624.НазначениеТОДляМодели this[int index]
        {
            get
            {
                return ((DataLine.TestGen270624.НазначениеТОДляМодели)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(DataLine.TestGen270624.НазначениеТОДляМодели dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

