//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [PublishName("Hardware")]
    [ClassStorage("Equipment")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "Номер as \'Номер\'",
            "ДатаПроизводства as \'Дата производства\'",
            "ДатаВводаВЭкспл as \'Дата ввода в экспл\'",
            "СрокГарантии as \'Срок гарантии\'",
            "Наработка as \'Наработка\'",
            "ДатаНаработки as \'Дата наработки\'",
            "Описание as \'Описание\'",
            "Тип as \'Тип\'",
            "Тип.Наименование as \'Наименование\'",
            "Статус as \'Статус\'",
            "Статус.Наименование as \'Наименование\'",
            "Ответственный as \'Ответственный\'",
            "Ответственный.Фамилия as \'Фамилия ответственного\'",
            "Ответственный.Имя as \'Имя ответственного\'",
            "Ответственный.Отчество as \'Отчество ответственного\'",
            "СервисныйДоговор as \'Сервисный договор\'",
            "СервисныйДоговор.Номер",
            "СервисныйДоговор.Дата as \'Дата сервисного договора\'",
            "СервисныйДоговор.СрокДействия as \'Срок действия сервисного договора\'",
            "Модель as \'Модель\'",
            "Модель.Наименование as \'Наименование\'",
            "Модель.Производитель.Наименование as \'Производитель модели\'",
            "ДоговорПоставки as \'Договор поставки\'",
            "ДоговорПоставки.Номер as \'Номер\'",
            "ДоговорПоставки.Дата as \'Дата договора поставки\'",
            "ДоговорПоставки.СрокДействия as \'Срок действия договора поставки\'",
            "МестоРасположения as \'Место расположения\'",
            "МестоРасположения.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Тип.Наименование",
            "Статус.Наименование",
            "СервисныйДоговор.Номер",
            "Модель.Наименование",
            "ДоговорПоставки.Номер",
            "МестоРасположения.Наименование"})]
    [MasterViewDefineAttribute("ОборудованиеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОборудованиеE", "Статус", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОборудованиеE", "Ответственный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ОборудованиеE", "СервисныйДоговор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ОборудованиеE", "Модель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОборудованиеE", "ДоговорПоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ОборудованиеE", "МестоРасположения", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ОборудованиеL", new string[] {
            "Номер as \'Номер\'",
            "ДатаПроизводства as \'Дата производства\'",
            "ДатаВводаВЭкспл as \'Дата ввода в экспл\'",
            "СрокГарантии as \'Срок гарантии\'",
            "Наработка as \'Наработка\'",
            "ДатаНаработки as \'Дата наработки\'",
            "Описание as \'Описание\'",
            "Тип.Наименование as \'Тип\'",
            "Статус.Наименование as \'Статус\'",
            "Ответственный.Фамилия as \'Ответственный\'",
            "СервисныйДоговор.Номер as \'Сервисный договор\'",
            "Модель.Наименование as \'Модель\'",
            "ДоговорПоставки.Номер as \'Договор поставки\'",
            "МестоРасположения.Наименование as \'Расположение\'"})]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаВводаВЭкспл;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаНаработки;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаПроизводства;

        private int fНаработка = 0;

        private string fНомер;

        private string fОписание;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fСрокГарантии;

        private DataLine.TestGen270624.Договор fДоговорПоставки;

        private DataLine.TestGen270624.Расположение fМестоРасположения;

        private DataLine.TestGen270624.МодельОборудования fМодель;

        private DataLine.TestGen270624.Сотрудник fОтветственный;

        private DataLine.TestGen270624.Договор fСервисныйДоговор;

        private DataLine.TestGen270624.СтатусОборудования fСтатус;

        private DataLine.TestGen270624.ТипОборудования fТип;

        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)


        /// <summary>
        /// ДатаВводаВЭкспл.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ДатаВводаВЭкспл CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ДатаВводаВЭкспл CustomAttributes)
        [PropertyStorage("DateOfCommissioning")]
        [PublishName("DateOfCommissioning")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаВводаВЭкспл
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ДатаВводаВЭкспл Get start)

                // *** End programmer edit section *** (Оборудование.ДатаВводаВЭкспл Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаВводаВЭкспл;
                // *** Start programmer edit section *** (Оборудование.ДатаВводаВЭкспл Get end)

                // *** End programmer edit section *** (Оборудование.ДатаВводаВЭкспл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ДатаВводаВЭкспл Set start)

                // *** End programmer edit section *** (Оборудование.ДатаВводаВЭкспл Set start)
                this.fДатаВводаВЭкспл = value;
                // *** Start programmer edit section *** (Оборудование.ДатаВводаВЭкспл Set end)

                // *** End programmer edit section *** (Оборудование.ДатаВводаВЭкспл Set end)
            }
        }

        /// <summary>
        /// ДатаНаработки.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ДатаНаработки CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ДатаНаработки CustomAttributes)
        [PropertyStorage("RunDate")]
        [PublishName("RunDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаНаработки
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ДатаНаработки Get start)

                // *** End programmer edit section *** (Оборудование.ДатаНаработки Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаНаработки;
                // *** Start programmer edit section *** (Оборудование.ДатаНаработки Get end)

                // *** End programmer edit section *** (Оборудование.ДатаНаработки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ДатаНаработки Set start)

                // *** End programmer edit section *** (Оборудование.ДатаНаработки Set start)
                this.fДатаНаработки = value;
                // *** Start programmer edit section *** (Оборудование.ДатаНаработки Set end)

                // *** End programmer edit section *** (Оборудование.ДатаНаработки Set end)
            }
        }

        /// <summary>
        /// ДатаПроизводства.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ДатаПроизводства CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ДатаПроизводства CustomAttributes)
        [PropertyStorage("ProductionDate")]
        [PublishName("ProductionDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаПроизводства
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ДатаПроизводства Get start)

                // *** End programmer edit section *** (Оборудование.ДатаПроизводства Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаПроизводства;
                // *** Start programmer edit section *** (Оборудование.ДатаПроизводства Get end)

                // *** End programmer edit section *** (Оборудование.ДатаПроизводства Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ДатаПроизводства Set start)

                // *** End programmer edit section *** (Оборудование.ДатаПроизводства Set start)
                this.fДатаПроизводства = value;
                // *** Start programmer edit section *** (Оборудование.ДатаПроизводства Set end)

                // *** End programmer edit section *** (Оборудование.ДатаПроизводства Set end)
            }
        }

        /// <summary>
        /// Наработка.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Наработка CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Наработка CustomAttributes)
        [PropertyStorage("OperatingTime")]
        [PublishName("OperatingTime")]
        public virtual int Наработка
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Наработка Get start)

                // *** End programmer edit section *** (Оборудование.Наработка Get start)
                int result = this.fНаработка;
                // *** Start programmer edit section *** (Оборудование.Наработка Get end)

                // *** End programmer edit section *** (Оборудование.Наработка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Наработка Set start)

                // *** End programmer edit section *** (Оборудование.Наработка Set start)
                this.fНаработка = value;
                // *** Start programmer edit section *** (Оборудование.Наработка Set end)

                // *** End programmer edit section *** (Оборудование.Наработка Set end)
            }
        }

        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Номер CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Номер CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Номер Get start)

                // *** End programmer edit section *** (Оборудование.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Оборудование.Номер Get end)

                // *** End programmer edit section *** (Оборудование.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Номер Set start)

                // *** End programmer edit section *** (Оборудование.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Оборудование.Номер Set end)

                // *** End programmer edit section *** (Оборудование.Номер Set end)
            }
        }

        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Описание CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Описание CustomAttributes)
        [PropertyStorage("Description")]
        [PublishName("Description")]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Описание Get start)

                // *** End programmer edit section *** (Оборудование.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Оборудование.Описание Get end)

                // *** End programmer edit section *** (Оборудование.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Описание Set start)

                // *** End programmer edit section *** (Оборудование.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Оборудование.Описание Set end)

                // *** End programmer edit section *** (Оборудование.Описание Set end)
            }
        }

        /// <summary>
        /// СрокГарантии.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.СрокГарантии CustomAttributes)

        // *** End programmer edit section *** (Оборудование.СрокГарантии CustomAttributes)
        [PropertyStorage("WarrantyPeriod")]
        [PublishName("WarrantyPeriod")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime СрокГарантии
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.СрокГарантии Get start)

                // *** End programmer edit section *** (Оборудование.СрокГарантии Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fСрокГарантии;
                // *** Start programmer edit section *** (Оборудование.СрокГарантии Get end)

                // *** End programmer edit section *** (Оборудование.СрокГарантии Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.СрокГарантии Set start)

                // *** End programmer edit section *** (Оборудование.СрокГарантии Set start)
                this.fСрокГарантии = value;
                // *** Start programmer edit section *** (Оборудование.СрокГарантии Set end)

                // *** End programmer edit section *** (Оборудование.СрокГарантии Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ДоговорПоставки CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ДоговорПоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "SupplyContract"})]
        [PublishName("SupplyContract")]
        public virtual DataLine.TestGen270624.Договор ДоговорПоставки
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ДоговорПоставки Get start)

                // *** End programmer edit section *** (Оборудование.ДоговорПоставки Get start)
                DataLine.TestGen270624.Договор result = this.fДоговорПоставки;
                // *** Start programmer edit section *** (Оборудование.ДоговорПоставки Get end)

                // *** End programmer edit section *** (Оборудование.ДоговорПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ДоговорПоставки Set start)

                // *** End programmer edit section *** (Оборудование.ДоговорПоставки Set start)
                this.fДоговорПоставки = value;
                // *** Start programmer edit section *** (Оборудование.ДоговорПоставки Set end)

                // *** End programmer edit section *** (Оборудование.ДоговорПоставки Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.МестоРасположения CustomAttributes)

        // *** End programmer edit section *** (Оборудование.МестоРасположения CustomAttributes)
        [PropertyStorage(new string[] {
                "Location"})]
        [PublishName("Location")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Расположение МестоРасположения
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.МестоРасположения Get start)

                // *** End programmer edit section *** (Оборудование.МестоРасположения Get start)
                DataLine.TestGen270624.Расположение result = this.fМестоРасположения;
                // *** Start programmer edit section *** (Оборудование.МестоРасположения Get end)

                // *** End programmer edit section *** (Оборудование.МестоРасположения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.МестоРасположения Set start)

                // *** End programmer edit section *** (Оборудование.МестоРасположения Set start)
                this.fМестоРасположения = value;
                // *** Start programmer edit section *** (Оборудование.МестоРасположения Set end)

                // *** End programmer edit section *** (Оборудование.МестоРасположения Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Модель CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Модель CustomAttributes)
        [PropertyStorage(new string[] {
                "Model"})]
        [PublishName("Model")]
        [NotNull()]
        public virtual DataLine.TestGen270624.МодельОборудования Модель
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Модель Get start)

                // *** End programmer edit section *** (Оборудование.Модель Get start)
                DataLine.TestGen270624.МодельОборудования result = this.fМодель;
                // *** Start programmer edit section *** (Оборудование.Модель Get end)

                // *** End programmer edit section *** (Оборудование.Модель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Модель Set start)

                // *** End programmer edit section *** (Оборудование.Модель Set start)
                this.fМодель = value;
                // *** Start programmer edit section *** (Оборудование.Модель Set end)

                // *** End programmer edit section *** (Оборудование.Модель Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Ответственный CustomAttributes)
        [PropertyStorage(new string[] {
                "Accountable"})]
        [PublishName("Accountable")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Сотрудник Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Ответственный Get start)

                // *** End programmer edit section *** (Оборудование.Ответственный Get start)
                DataLine.TestGen270624.Сотрудник result = this.fОтветственный;
                // *** Start programmer edit section *** (Оборудование.Ответственный Get end)

                // *** End programmer edit section *** (Оборудование.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Ответственный Set start)

                // *** End programmer edit section *** (Оборудование.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Оборудование.Ответственный Set end)

                // *** End programmer edit section *** (Оборудование.Ответственный Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.СервисныйДоговор CustomAttributes)

        // *** End programmer edit section *** (Оборудование.СервисныйДоговор CustomAttributes)
        [PropertyStorage(new string[] {
                "ServiceContract"})]
        [PublishName("ServiceContract")]
        public virtual DataLine.TestGen270624.Договор СервисныйДоговор
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.СервисныйДоговор Get start)

                // *** End programmer edit section *** (Оборудование.СервисныйДоговор Get start)
                DataLine.TestGen270624.Договор result = this.fСервисныйДоговор;
                // *** Start programmer edit section *** (Оборудование.СервисныйДоговор Get end)

                // *** End programmer edit section *** (Оборудование.СервисныйДоговор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.СервисныйДоговор Set start)

                // *** End programmer edit section *** (Оборудование.СервисныйДоговор Set start)
                this.fСервисныйДоговор = value;
                // *** Start programmer edit section *** (Оборудование.СервисныйДоговор Set end)

                // *** End programmer edit section *** (Оборудование.СервисныйДоговор Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Статус CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Статус CustomAttributes)
        [PropertyStorage(new string[] {
                "Status"})]
        [PublishName("Status")]
        [NotNull()]
        public virtual DataLine.TestGen270624.СтатусОборудования Статус
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Статус Get start)

                // *** End programmer edit section *** (Оборудование.Статус Get start)
                DataLine.TestGen270624.СтатусОборудования result = this.fСтатус;
                // *** Start programmer edit section *** (Оборудование.Статус Get end)

                // *** End programmer edit section *** (Оборудование.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Статус Set start)

                // *** End programmer edit section *** (Оборудование.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Оборудование.Статус Set end)

                // *** End programmer edit section *** (Оборудование.Статус Set end)
            }
        }

        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Тип CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Type"})]
        [PublishName("Type")]
        [NotNull()]
        public virtual DataLine.TestGen270624.ТипОборудования Тип
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Тип Get start)

                // *** End programmer edit section *** (Оборудование.Тип Get start)
                DataLine.TestGen270624.ТипОборудования result = this.fТип;
                // *** Start programmer edit section *** (Оборудование.Тип Get end)

                // *** End programmer edit section *** (Оборудование.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Тип Set start)

                // *** End programmer edit section *** (Оборудование.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Оборудование.Тип Set end)

                // *** End programmer edit section *** (Оборудование.Тип Set end)
            }
        }

        // *** Start programmer edit section *** (Оборудование.ЗапланироватьТО CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ЗапланироватьТО CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void ЗапланироватьТО()
        {
            // *** Start programmer edit section *** (Оборудование.ЗапланироватьТО method implementation)

            return;
            // *** End programmer edit section *** (Оборудование.ЗапланироватьТО method implementation)
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(DataLine.TestGen270624.Оборудование));
                }
            }

            /// <summary>
            /// "ОборудованиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеL", typeof(DataLine.TestGen270624.Оборудование));
                }
            }
        }
    }
}

