//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Операция ТО.
    /// </summary>
    // *** Start programmer edit section *** (ОперацияТО CustomAttributes)

    // *** End programmer edit section *** (ОперацияТО CustomAttributes)
    [PublishName("MaintenanceOperation")]
    [ClassStorage("MaintenanceOperation")]
    [AutoAltered()]
    [Caption("Операция ТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОперацияТОE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ОперацияТОL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ОперацияТО : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        private DataLine.TestGen270624.ПрограммаТО fПрограммаТО;

        // *** Start programmer edit section *** (ОперацияТО CustomMembers)

        // *** End programmer edit section *** (ОперацияТО CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ОперацияТО.Наименование CustomAttributes)

        // *** End programmer edit section *** (ОперацияТО.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ОперацияТО.Наименование Get start)

                // *** End programmer edit section *** (ОперацияТО.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ОперацияТО.Наименование Get end)

                // *** End programmer edit section *** (ОперацияТО.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОперацияТО.Наименование Set start)

                // *** End programmer edit section *** (ОперацияТО.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ОперацияТО.Наименование Set end)

                // *** End programmer edit section *** (ОперацияТО.Наименование Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку DataLine.TestGen270624.ПрограммаТО.
        /// </summary>
        // *** Start programmer edit section *** (ОперацияТО.ПрограммаТО CustomAttributes)

        // *** End programmer edit section *** (ОперацияТО.ПрограммаТО CustomAttributes)
        [Agregator()]
        [PublishName("MaintenanceProgram")]
        [NotNull()]
        [PropertyStorage(new string[] {
                "MaintenanceProgram"})]
        public virtual DataLine.TestGen270624.ПрограммаТО ПрограммаТО
        {
            get
            {
                // *** Start programmer edit section *** (ОперацияТО.ПрограммаТО Get start)

                // *** End programmer edit section *** (ОперацияТО.ПрограммаТО Get start)
                DataLine.TestGen270624.ПрограммаТО result = this.fПрограммаТО;
                // *** Start programmer edit section *** (ОперацияТО.ПрограммаТО Get end)

                // *** End programmer edit section *** (ОперацияТО.ПрограммаТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОперацияТО.ПрограммаТО Set start)

                // *** End programmer edit section *** (ОперацияТО.ПрограммаТО Set start)
                this.fПрограммаТО = value;
                // *** Start programmer edit section *** (ОперацияТО.ПрограммаТО Set end)

                // *** End programmer edit section *** (ОперацияТО.ПрограммаТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ОперацияТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацияТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацияТОE", typeof(DataLine.TestGen270624.ОперацияТО));
                }
            }

            /// <summary>
            /// "ОперацияТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацияТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацияТОL", typeof(DataLine.TestGen270624.ОперацияТО));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of ОперацияТО.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОперацияТО CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОперацияТО CustomAttributes)
    public class DetailArrayOfОперацияТО : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (DataLine.TestGen270624.DetailArrayOfОперацияТО members)

        // *** End programmer edit section *** (DataLine.TestGen270624.DetailArrayOfОперацияТО members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОперацияТО by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОперацияТО.
        /// </summary>
        public DetailArrayOfОперацияТО(DataLine.TestGen270624.ПрограммаТО fПрограммаТО) : 
                base(typeof(ОперацияТО), ((ICSSoft.STORMNET.DataObject)(fПрограммаТО)))
        {
        }

        public DataLine.TestGen270624.ОперацияТО this[int index]
        {
            get
            {
                return ((DataLine.TestGen270624.ОперацияТО)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(DataLine.TestGen270624.ОперацияТО dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

