//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Периодичность.
    /// </summary>
    // *** Start programmer edit section *** (Периодичность CustomAttributes)

    // *** End programmer edit section *** (Периодичность CustomAttributes)
    [PublishName("Periodicity")]
    [ClassStorage("Periodicity")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PeriodicityE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("PeriodicityL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Периодичность : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        // *** Start programmer edit section *** (Периодичность CustomMembers)

        // *** End programmer edit section *** (Периодичность CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Периодичность.Наименование CustomAttributes)

        // *** End programmer edit section *** (Периодичность.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Периодичность.Наименование Get start)

                // *** End programmer edit section *** (Периодичность.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Периодичность.Наименование Get end)

                // *** End programmer edit section *** (Периодичность.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Периодичность.Наименование Set start)

                // *** End programmer edit section *** (Периодичность.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Периодичность.Наименование Set end)

                // *** End programmer edit section *** (Периодичность.Наименование Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "PeriodicityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PeriodicityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PeriodicityE", typeof(DataLine.TestGen270624.Периодичность));
                }
            }

            /// <summary>
            /// "PeriodicityL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PeriodicityL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PeriodicityL", typeof(DataLine.TestGen270624.Периодичность));
                }
            }
        }
    }
}

