//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План операция ТО.
    /// </summary>
    // *** Start programmer edit section *** (ПланОперацияТО CustomAttributes)

    // *** End programmer edit section *** (ПланОперацияТО CustomAttributes)
    [PublishName("ScheduledMaintenanceOperation")]
    [ClassStorage("ScheduledMaintenanceOperation")]
    [AutoAltered()]
    [Caption("Плановая операция ТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланОперацияТОE", new string[] {
            "ДатаВыполнения as \'Дата выполнения\'",
            "ОперацияТО as \'Операция ТО\'",
            "ОперацияТО.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ОперацияТО.Наименование"})]
    [MasterViewDefineAttribute("ПланОперацияТОE", "ОперацияТО", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПланОперацияТОL", new string[] {
            "ДатаВыполнения as \'Дата выполнения\'",
            "ОперацияТО as \'Операция ТО\'",
            "ОперацияТО.Наименование as \'Наименование операции\'"}, Hidden=new string[] {
            "ОперацияТО"})]
    [MasterViewDefineAttribute("ПланОперацияТОL", "ОперацияТО", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ПланОперацияТО : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fДатаВыполнения;

        private DataLine.TestGen270624.ОперацияТО fОперацияТО;

        private DataLine.TestGen270624.ПланТО fПланТО;

        // *** Start programmer edit section *** (ПланОперацияТО CustomMembers)

        // *** End programmer edit section *** (ПланОперацияТО CustomMembers)


        /// <summary>
        /// ДатаВыполнения.
        /// </summary>
        // *** Start programmer edit section *** (ПланОперацияТО.ДатаВыполнения CustomAttributes)

        // *** End programmer edit section *** (ПланОперацияТО.ДатаВыполнения CustomAttributes)
        [PropertyStorage("ExecutionDate")]
        [PublishName("ExecutionDate")]
        [NotNull()]
        public virtual System.DateTime ДатаВыполнения
        {
            get
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ДатаВыполнения Get start)

                // *** End programmer edit section *** (ПланОперацияТО.ДатаВыполнения Get start)
                System.DateTime result = this.fДатаВыполнения;
                // *** Start programmer edit section *** (ПланОперацияТО.ДатаВыполнения Get end)

                // *** End programmer edit section *** (ПланОперацияТО.ДатаВыполнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ДатаВыполнения Set start)

                // *** End programmer edit section *** (ПланОперацияТО.ДатаВыполнения Set start)
                this.fДатаВыполнения = value;
                // *** Start programmer edit section *** (ПланОперацияТО.ДатаВыполнения Set end)

                // *** End programmer edit section *** (ПланОперацияТО.ДатаВыполнения Set end)
            }
        }

        /// <summary>
        /// План операция ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПланОперацияТО.ОперацияТО CustomAttributes)

        // *** End programmer edit section *** (ПланОперацияТО.ОперацияТО CustomAttributes)
        [PropertyStorage(new string[] {
                "MaintenanceOperation"})]
        [PublishName("MaintenanceOperation")]
        [NotNull()]
        public virtual DataLine.TestGen270624.ОперацияТО ОперацияТО
        {
            get
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ОперацияТО Get start)

                // *** End programmer edit section *** (ПланОперацияТО.ОперацияТО Get start)
                DataLine.TestGen270624.ОперацияТО result = this.fОперацияТО;
                // *** Start programmer edit section *** (ПланОперацияТО.ОперацияТО Get end)

                // *** End programmer edit section *** (ПланОперацияТО.ОперацияТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ОперацияТО Set start)

                // *** End programmer edit section *** (ПланОперацияТО.ОперацияТО Set start)
                this.fОперацияТО = value;
                // *** Start programmer edit section *** (ПланОперацияТО.ОперацияТО Set end)

                // *** End programmer edit section *** (ПланОперацияТО.ОперацияТО Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку DataLine.TestGen270624.ПланТО.
        /// </summary>
        // *** Start programmer edit section *** (ПланОперацияТО.ПланТО CustomAttributes)

        // *** End programmer edit section *** (ПланОперацияТО.ПланТО CustomAttributes)
        [Agregator()]
        [PublishName("MaintenancePlan")]
        [NotNull()]
        [PropertyStorage(new string[] {
                "MaintenancePlan"})]
        public virtual DataLine.TestGen270624.ПланТО ПланТО
        {
            get
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ПланТО Get start)

                // *** End programmer edit section *** (ПланОперацияТО.ПланТО Get start)
                DataLine.TestGen270624.ПланТО result = this.fПланТО;
                // *** Start programmer edit section *** (ПланОперацияТО.ПланТО Get end)

                // *** End programmer edit section *** (ПланОперацияТО.ПланТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланОперацияТО.ПланТО Set start)

                // *** End programmer edit section *** (ПланОперацияТО.ПланТО Set start)
                this.fПланТО = value;
                // *** Start programmer edit section *** (ПланОперацияТО.ПланТО Set end)

                // *** End programmer edit section *** (ПланОперацияТО.ПланТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ПланОперацияТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланОперацияТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланОперацияТОE", typeof(DataLine.TestGen270624.ПланОперацияТО));
                }
            }

            /// <summary>
            /// "ПланОперацияТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланОперацияТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланОперацияТОL", typeof(DataLine.TestGen270624.ПланОперацияТО));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of ПланОперацияТО.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПланОперацияТО CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПланОперацияТО CustomAttributes)
    public class DetailArrayOfПланОперацияТО : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (DataLine.TestGen270624.DetailArrayOfПланОперацияТО members)

        // *** End programmer edit section *** (DataLine.TestGen270624.DetailArrayOfПланОперацияТО members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПланОперацияТО by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПланОперацияТО.
        /// </summary>
        public DetailArrayOfПланОперацияТО(DataLine.TestGen270624.ПланТО fПланТО) : 
                base(typeof(ПланОперацияТО), ((ICSSoft.STORMNET.DataObject)(fПланТО)))
        {
        }

        public DataLine.TestGen270624.ПланОперацияТО this[int index]
        {
            get
            {
                return ((DataLine.TestGen270624.ПланОперацияТО)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(DataLine.TestGen270624.ПланОперацияТО dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

