//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План ТО.
    /// </summary>
    // *** Start programmer edit section *** (ПланТО CustomAttributes)

    // *** End programmer edit section *** (ПланТО CustomAttributes)
    [PublishName("MaintenancePlan")]
    [ClassStorage("MaintenancePlan")]
    [AutoAltered()]
    [Caption("План ТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланТОE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Номер as \'Номер\'",
            "Оборудование.Модель.Наименование as \'Модель оборудования\'",
            "Оборудование.Тип.Наименование as \'Тип оборудования\'",
            "Оборудование.Статус.Наименование as \'Статус оборудования\'",
            "Оборудование.Ответственный.Фамилия as \'Фамилия ответственного\'",
            "Оборудование.СервисныйДоговор.Номер as \'Номер сервисного договора\'",
            "Оборудование.МестоРасположения.Наименование as \'Место расположения оборудования\'"}, Hidden=new string[] {
            "Оборудование.Номер"})]
    [AssociatedDetailViewAttribute("ПланТОE", "ПлановыеОперацииТО", "ПланОперацияТОE", true, "", "Плановые операции ТО", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПланТОE", "Оборудование", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ПланТОL", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Оборудование.Номер as \'Номер\'",
            "Оборудование.Модель.Наименование as \'Модель\'",
            "Оборудование.Модель.Производитель.Наименование as \'Производитель\'"})]
    public class ПланТО : ICSSoft.STORMNET.DataObject
    {

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаНачала;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончания;

        private DataLine.TestGen270624.Оборудование fОборудование;

        private DataLine.TestGen270624.DetailArrayOfПланОперацияТО fПлановыеОперацииТО;

        // *** Start programmer edit section *** (ПланТО CustomMembers)

        // *** End programmer edit section *** (ПланТО CustomMembers)


        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ПланТО.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ПланТО.ДатаНачала CustomAttributes)
        [PropertyStorage("StartDate")]
        [PublishName("StartDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ПланТО.ДатаНачала Get start)

                // *** End programmer edit section *** (ПланТО.ДатаНачала Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ПланТО.ДатаНачала Get end)

                // *** End programmer edit section *** (ПланТО.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланТО.ДатаНачала Set start)

                // *** End programmer edit section *** (ПланТО.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ПланТО.ДатаНачала Set end)

                // *** End programmer edit section *** (ПланТО.ДатаНачала Set end)
            }
        }

        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ПланТО.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ПланТО.ДатаОкончания CustomAttributes)
        [PropertyStorage("EndDate")]
        [PublishName("EndDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ПланТО.ДатаОкончания Get start)

                // *** End programmer edit section *** (ПланТО.ДатаОкончания Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ПланТО.ДатаОкончания Get end)

                // *** End programmer edit section *** (ПланТО.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланТО.ДатаОкончания Set start)

                // *** End programmer edit section *** (ПланТО.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ПланТО.ДатаОкончания Set end)

                // *** End programmer edit section *** (ПланТО.ДатаОкончания Set end)
            }
        }

        /// <summary>
        /// План ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПланТО.Оборудование CustomAttributes)

        // *** End programmer edit section *** (ПланТО.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Equipment"})]
        [PublishName("Equipment")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (ПланТО.Оборудование Get start)

                // *** End programmer edit section *** (ПланТО.Оборудование Get start)
                DataLine.TestGen270624.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (ПланТО.Оборудование Get end)

                // *** End programmer edit section *** (ПланТО.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланТО.Оборудование Set start)

                // *** End programmer edit section *** (ПланТО.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (ПланТО.Оборудование Set end)

                // *** End programmer edit section *** (ПланТО.Оборудование Set end)
            }
        }

        /// <summary>
        /// План ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПланТО.ПлановыеОперацииТО CustomAttributes)

        // *** End programmer edit section *** (ПланТО.ПлановыеОперацииТО CustomAttributes)
        [PublishName("ScheduledMaintenanceOperation")]
        public virtual DataLine.TestGen270624.DetailArrayOfПланОперацияТО ПлановыеОперацииТО
        {
            get
            {
                // *** Start programmer edit section *** (ПланТО.ПлановыеОперацииТО Get start)

                // *** End programmer edit section *** (ПланТО.ПлановыеОперацииТО Get start)
                if ((this.fПлановыеОперацииТО == null))
                {
                    this.fПлановыеОперацииТО = new DataLine.TestGen270624.DetailArrayOfПланОперацияТО(this);
                }
                DataLine.TestGen270624.DetailArrayOfПланОперацияТО result = this.fПлановыеОперацииТО;
                // *** Start programmer edit section *** (ПланТО.ПлановыеОперацииТО Get end)

                // *** End programmer edit section *** (ПланТО.ПлановыеОперацииТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланТО.ПлановыеОперацииТО Set start)

                // *** End programmer edit section *** (ПланТО.ПлановыеОперацииТО Set start)
                this.fПлановыеОперацииТО = value;
                // *** Start programmer edit section *** (ПланТО.ПлановыеОперацииТО Set end)

                // *** End programmer edit section *** (ПланТО.ПлановыеОперацииТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ПланТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланТОE", typeof(DataLine.TestGen270624.ПланТО));
                }
            }

            /// <summary>
            /// "ПланТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланТОL", typeof(DataLine.TestGen270624.ПланТО));
                }
            }
        }
    }
}

