//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Программа ТО.
    /// </summary>
    // *** Start programmer edit section *** (ПрограммаТО CustomAttributes)

    // *** End programmer edit section *** (ПрограммаТО CustomAttributes)
    [PublishName("MaintenanceProgram")]
    [ClassStorage("MaintenanceProgram")]
    [AutoAltered()]
    [Caption("Программа ТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрограммаТОE", new string[] {
            "Наименование as \'Наименование\'",
            "Периодичность as \'Периодичность\'",
            "Периодичность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Периодичность.Наименование"})]
    [AssociatedDetailViewAttribute("ПрограммаТОE", "МоделиОборудования", "НазначениеТОДляМоделиE", true, "", "Модели оборудования", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПрограммаТОE", "ОперацииТО", "ОперацияТОE", true, "", "Операции ТО", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПрограммаТОE", "Периодичность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПрограммаТОL", new string[] {
            "Наименование as \'Наименование\'",
            "Периодичность.Наименование as \'Периодичность\'"})]
    public class ПрограммаТО : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        private DataLine.TestGen270624.Периодичность fПериодичность;

        private DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели fМоделиОборудования;

        private DataLine.TestGen270624.DetailArrayOfОперацияТО fОперацииТО;

        // *** Start programmer edit section *** (ПрограммаТО CustomMembers)

        // *** End programmer edit section *** (ПрограммаТО CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ПрограммаТО.Наименование CustomAttributes)

        // *** End programmer edit section *** (ПрограммаТО.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ПрограммаТО.Наименование Get start)

                // *** End programmer edit section *** (ПрограммаТО.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ПрограммаТО.Наименование Get end)

                // *** End programmer edit section *** (ПрограммаТО.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрограммаТО.Наименование Set start)

                // *** End programmer edit section *** (ПрограммаТО.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ПрограммаТО.Наименование Set end)

                // *** End programmer edit section *** (ПрограммаТО.Наименование Set end)
            }
        }

        /// <summary>
        /// Программа ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПрограммаТО.Периодичность CustomAttributes)

        // *** End programmer edit section *** (ПрограммаТО.Периодичность CustomAttributes)
        [PropertyStorage(new string[] {
                "Periodicity"})]
        [PublishName("Periodicity")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Периодичность Периодичность
        {
            get
            {
                // *** Start programmer edit section *** (ПрограммаТО.Периодичность Get start)

                // *** End programmer edit section *** (ПрограммаТО.Периодичность Get start)
                DataLine.TestGen270624.Периодичность result = this.fПериодичность;
                // *** Start programmer edit section *** (ПрограммаТО.Периодичность Get end)

                // *** End programmer edit section *** (ПрограммаТО.Периодичность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрограммаТО.Периодичность Set start)

                // *** End programmer edit section *** (ПрограммаТО.Периодичность Set start)
                this.fПериодичность = value;
                // *** Start programmer edit section *** (ПрограммаТО.Периодичность Set end)

                // *** End programmer edit section *** (ПрограммаТО.Периодичность Set end)
            }
        }

        /// <summary>
        /// Программа ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПрограммаТО.МоделиОборудования CustomAttributes)

        // *** End programmer edit section *** (ПрограммаТО.МоделиОборудования CustomAttributes)
        [PublishName("PurposeOfTheMaintenanceModel")]
        public virtual DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели МоделиОборудования
        {
            get
            {
                // *** Start programmer edit section *** (ПрограммаТО.МоделиОборудования Get start)

                // *** End programmer edit section *** (ПрограммаТО.МоделиОборудования Get start)
                if ((this.fМоделиОборудования == null))
                {
                    this.fМоделиОборудования = new DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели(this);
                }
                DataLine.TestGen270624.DetailArrayOfНазначениеТОДляМодели result = this.fМоделиОборудования;
                // *** Start programmer edit section *** (ПрограммаТО.МоделиОборудования Get end)

                // *** End programmer edit section *** (ПрограммаТО.МоделиОборудования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрограммаТО.МоделиОборудования Set start)

                // *** End programmer edit section *** (ПрограммаТО.МоделиОборудования Set start)
                this.fМоделиОборудования = value;
                // *** Start programmer edit section *** (ПрограммаТО.МоделиОборудования Set end)

                // *** End programmer edit section *** (ПрограммаТО.МоделиОборудования Set end)
            }
        }

        /// <summary>
        /// Программа ТО.
        /// </summary>
        // *** Start programmer edit section *** (ПрограммаТО.ОперацииТО CustomAttributes)

        // *** End programmer edit section *** (ПрограммаТО.ОперацииТО CustomAttributes)
        [PublishName("MaintenanceOperation")]
        public virtual DataLine.TestGen270624.DetailArrayOfОперацияТО ОперацииТО
        {
            get
            {
                // *** Start programmer edit section *** (ПрограммаТО.ОперацииТО Get start)

                // *** End programmer edit section *** (ПрограммаТО.ОперацииТО Get start)
                if ((this.fОперацииТО == null))
                {
                    this.fОперацииТО = new DataLine.TestGen270624.DetailArrayOfОперацияТО(this);
                }
                DataLine.TestGen270624.DetailArrayOfОперацияТО result = this.fОперацииТО;
                // *** Start programmer edit section *** (ПрограммаТО.ОперацииТО Get end)

                // *** End programmer edit section *** (ПрограммаТО.ОперацииТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрограммаТО.ОперацииТО Set start)

                // *** End programmer edit section *** (ПрограммаТО.ОперацииТО Set start)
                this.fОперацииТО = value;
                // *** Start programmer edit section *** (ПрограммаТО.ОперацииТО Set end)

                // *** End programmer edit section *** (ПрограммаТО.ОперацииТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ПрограммаТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрограммаТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрограммаТОE", typeof(DataLine.TestGen270624.ПрограммаТО));
                }
            }

            /// <summary>
            /// "ПрограммаТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрограммаТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрограммаТОL", typeof(DataLine.TestGen270624.ПрограммаТО));
                }
            }
        }
    }
}

