//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расположение.
    /// </summary>
    // *** Start programmer edit section *** (Расположение CustomAttributes)

    // *** End programmer edit section *** (Расположение CustomAttributes)
    [PublishName("Location")]
    [ClassStorage("Location")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасположениеE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("РасположениеL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Расположение : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        // *** Start programmer edit section *** (Расположение CustomMembers)

        // *** End programmer edit section *** (Расположение CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Расположение.Наименование CustomAttributes)

        // *** End programmer edit section *** (Расположение.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Расположение.Наименование Get start)

                // *** End programmer edit section *** (Расположение.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Расположение.Наименование Get end)

                // *** End programmer edit section *** (Расположение.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расположение.Наименование Set start)

                // *** End programmer edit section *** (Расположение.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Расположение.Наименование Set end)

                // *** End programmer edit section *** (Расположение.Наименование Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "РасположениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасположениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасположениеE", typeof(DataLine.TestGen270624.Расположение));
                }
            }

            /// <summary>
            /// "РасположениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасположениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасположениеL", typeof(DataLine.TestGen270624.Расположение));
                }
            }
        }
    }
}

