//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус оборудования.
    /// </summary>
    // *** Start programmer edit section *** (СтатусОборудования CustomAttributes)

    // *** End programmer edit section *** (СтатусОборудования CustomAttributes)
    [PublishName("EquipmentStatus")]
    [ClassStorage("StatusOfTheEquipment")]
    [AutoAltered()]
    [Caption("Статус оборудования")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтатусОборудованияE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("СтатусОборудованияL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class СтатусОборудования : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        // *** Start programmer edit section *** (СтатусОборудования CustomMembers)

        // *** End programmer edit section *** (СтатусОборудования CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СтатусОборудования.Наименование CustomAttributes)

        // *** End programmer edit section *** (СтатусОборудования.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СтатусОборудования.Наименование Get start)

                // *** End programmer edit section *** (СтатусОборудования.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СтатусОборудования.Наименование Get end)

                // *** End programmer edit section *** (СтатусОборудования.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтатусОборудования.Наименование Set start)

                // *** End programmer edit section *** (СтатусОборудования.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СтатусОборудования.Наименование Set end)

                // *** End programmer edit section *** (СтатусОборудования.Наименование Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "СтатусОборудованияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатусОборудованияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатусОборудованияE", typeof(DataLine.TestGen270624.СтатусОборудования));
                }
            }

            /// <summary>
            /// "СтатусОборудованияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатусОборудованияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатусОборудованияL", typeof(DataLine.TestGen270624.СтатусОборудования));
                }
            }
        }
    }
}

