//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оборудования.
    /// </summary>
    // *** Start programmer edit section *** (ТипОборудования CustomAttributes)

    // *** End programmer edit section *** (ТипОборудования CustomAttributes)
    [PublishName("EquipmentType")]
    [ClassStorage("TypeOfEquipment")]
    [AutoAltered()]
    [Caption("Тип оборудования")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипОборудованияE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ТипОборудованияL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ТипОборудования : ICSSoft.STORMNET.DataObject
    {

        private string fНаименование;

        // *** Start programmer edit section *** (ТипОборудования CustomMembers)

        // *** End programmer edit section *** (ТипОборудования CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ТипОборудования.Наименование CustomAttributes)

        // *** End programmer edit section *** (ТипОборудования.Наименование CustomAttributes)
        [PropertyStorage("Name")]
        [PublishName("Name")]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ТипОборудования.Наименование Get start)

                // *** End programmer edit section *** (ТипОборудования.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ТипОборудования.Наименование Get end)

                // *** End programmer edit section *** (ТипОборудования.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипОборудования.Наименование Set start)

                // *** End programmer edit section *** (ТипОборудования.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ТипОборудования.Наименование Set end)

                // *** End programmer edit section *** (ТипОборудования.Наименование Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ТипОборудованияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипОборудованияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипОборудованияE", typeof(DataLine.TestGen270624.ТипОборудования));
                }
            }

            /// <summary>
            /// "ТипОборудованияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипОборудованияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипОборудованияL", typeof(DataLine.TestGen270624.ТипОборудования));
                }
            }
        }
    }
}

