//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.TestGen270624
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факт ТО.
    /// </summary>
    // *** Start programmer edit section *** (ФактТО CustomAttributes)

    // *** End programmer edit section *** (ФактТО CustomAttributes)
    [PublishName("FactOfTheMaintenance")]
    [ClassStorage("FactOfTheMaintenance")]
    [AutoAltered()]
    [Caption("Факт ТО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФактТОE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "СканПротокола as \'Скан протокола\'",
            "Успешно as \'Успешно\'",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Номер as \'Номер\'",
            "ПланТО as \'План ТО\'",
            "ПланТО.ДатаНачала as \'Дата начала\'",
            "ПланТО.ДатаОкончания as \'Дата окончания\'",
            "ПланТО.Оборудование.Номер as \'Номер оборудования\'",
            "ПланТО.Оборудование.Тип.Наименование as \'Тип оборудования\'",
            "ПланТО.Оборудование.Модель.Наименование as \'Модель оборудования\'",
            "ПланТО.Оборудование.Модель.Производитель.Наименование as \'Производитель оборудова" +
                "ния\'"}, Hidden=new string[] {
            "Оборудование.Номер"})]
    [AssociatedDetailViewAttribute("ФактТОE", "ФактическиеОперацииТО", "ФактОперацияТОE", true, "", "Фактические операции ТО", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ФактТОE", "Оборудование", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ФактТОL", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "СканПротокола as \'Скан протокола\'",
            "Успешно as \'Успешно\'",
            "Оборудование.Номер as \'Номер\'",
            "Оборудование.Модель.Наименование as \'Модель оборудования\'",
            "Оборудование.Модель.Производитель.Наименование as \'Производитель оборудования\'",
            "Оборудование.Тип.Наименование as \'Тип оборудования\'",
            "ПланТО.ДатаНачала as \'Дата начала\'"})]
    public class ФактТО : ICSSoft.STORMNET.DataObject
    {

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаНачала;

        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончания;

        private string fСканПротокола;

        private DataLine.TestGen270624.Оборудование fОборудование;

        private DataLine.TestGen270624.ПланТО fПланТО;

        private DataLine.TestGen270624.DetailArrayOfФактОперацияТО fФактическиеОперацииТО;

        // *** Start programmer edit section *** (ФактТО CustomMembers)

        // *** End programmer edit section *** (ФактТО CustomMembers)


        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ФактТО.ДатаНачала CustomAttributes)
        [PropertyStorage("StartDate")]
        [PublishName("StartDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.ДатаНачала Get start)

                // *** End programmer edit section *** (ФактТО.ДатаНачала Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ФактТО.ДатаНачала Get end)

                // *** End programmer edit section *** (ФактТО.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.ДатаНачала Set start)

                // *** End programmer edit section *** (ФактТО.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ФактТО.ДатаНачала Set end)

                // *** End programmer edit section *** (ФактТО.ДатаНачала Set end)
            }
        }

        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ФактТО.ДатаОкончания CustomAttributes)
        [PropertyStorage("EndDate")]
        [PublishName("EndDate")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.ДатаОкончания Get start)

                // *** End programmer edit section *** (ФактТО.ДатаОкончания Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ФактТО.ДатаОкончания Get end)

                // *** End programmer edit section *** (ФактТО.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.ДатаОкончания Set start)

                // *** End programmer edit section *** (ФактТО.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ФактТО.ДатаОкончания Set end)

                // *** End programmer edit section *** (ФактТО.ДатаОкончания Set end)
            }
        }

        /// <summary>
        /// СканПротокола.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.СканПротокола CustomAttributes)

        // *** End programmer edit section *** (ФактТО.СканПротокола CustomAttributes)
        [PropertyStorage("ScanProtocol")]
        [PublishName("ScanProtocol")]
        public virtual string СканПротокола
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.СканПротокола Get start)

                // *** End programmer edit section *** (ФактТО.СканПротокола Get start)
                string result = this.fСканПротокола;
                // *** Start programmer edit section *** (ФактТО.СканПротокола Get end)

                // *** End programmer edit section *** (ФактТО.СканПротокола Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.СканПротокола Set start)

                // *** End programmer edit section *** (ФактТО.СканПротокола Set start)
                this.fСканПротокола = value;
                // *** Start programmer edit section *** (ФактТО.СканПротокола Set end)

                // *** End programmer edit section *** (ФактТО.СканПротокола Set end)
            }
        }

        /// <summary>
        /// Успешно.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.Успешно CustomAttributes)

        // *** End programmer edit section *** (ФактТО.Успешно CustomAttributes)
        [PropertyStorage("Successfully")]
        [ICSSoft.STORMNET.NotStored()]
        [PublishName("Successfully")]
        [NotNull()]
        public virtual bool Успешно
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.Успешно Get)

                return false;
                // *** End programmer edit section *** (ФактТО.Успешно Get)
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.Успешно Set)

                // *** End programmer edit section *** (ФактТО.Успешно Set)
            }
        }

        /// <summary>
        /// Факт ТО.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.Оборудование CustomAttributes)

        // *** End programmer edit section *** (ФактТО.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Equipment"})]
        [PublishName("Equipment")]
        [NotNull()]
        public virtual DataLine.TestGen270624.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.Оборудование Get start)

                // *** End programmer edit section *** (ФактТО.Оборудование Get start)
                DataLine.TestGen270624.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (ФактТО.Оборудование Get end)

                // *** End programmer edit section *** (ФактТО.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.Оборудование Set start)

                // *** End programmer edit section *** (ФактТО.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (ФактТО.Оборудование Set end)

                // *** End programmer edit section *** (ФактТО.Оборудование Set end)
            }
        }

        /// <summary>
        /// Факт ТО.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.ПланТО CustomAttributes)

        // *** End programmer edit section *** (ФактТО.ПланТО CustomAttributes)
        [PropertyStorage(new string[] {
                "MaintenancePlan"})]
        [PublishName("MaintenancePlan")]
        public virtual DataLine.TestGen270624.ПланТО ПланТО
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.ПланТО Get start)

                // *** End programmer edit section *** (ФактТО.ПланТО Get start)
                DataLine.TestGen270624.ПланТО result = this.fПланТО;
                // *** Start programmer edit section *** (ФактТО.ПланТО Get end)

                // *** End programmer edit section *** (ФактТО.ПланТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.ПланТО Set start)

                // *** End programmer edit section *** (ФактТО.ПланТО Set start)
                this.fПланТО = value;
                // *** Start programmer edit section *** (ФактТО.ПланТО Set end)

                // *** End programmer edit section *** (ФактТО.ПланТО Set end)
            }
        }

        /// <summary>
        /// Факт ТО.
        /// </summary>
        // *** Start programmer edit section *** (ФактТО.ФактическиеОперацииТО CustomAttributes)

        // *** End programmer edit section *** (ФактТО.ФактическиеОперацииТО CustomAttributes)
        [PublishName("FactOperationOfTheMaintenance")]
        public virtual DataLine.TestGen270624.DetailArrayOfФактОперацияТО ФактическиеОперацииТО
        {
            get
            {
                // *** Start programmer edit section *** (ФактТО.ФактическиеОперацииТО Get start)

                // *** End programmer edit section *** (ФактТО.ФактическиеОперацииТО Get start)
                if ((this.fФактическиеОперацииТО == null))
                {
                    this.fФактическиеОперацииТО = new DataLine.TestGen270624.DetailArrayOfФактОперацияТО(this);
                }
                DataLine.TestGen270624.DetailArrayOfФактОперацияТО result = this.fФактическиеОперацииТО;
                // *** Start programmer edit section *** (ФактТО.ФактическиеОперацииТО Get end)

                // *** End programmer edit section *** (ФактТО.ФактическиеОперацииТО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФактТО.ФактическиеОперацииТО Set start)

                // *** End programmer edit section *** (ФактТО.ФактическиеОперацииТО Set start)
                this.fФактическиеОперацииТО = value;
                // *** Start programmer edit section *** (ФактТО.ФактическиеОперацииТО Set end)

                // *** End programmer edit section *** (ФактТО.ФактическиеОперацииТО Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ФактТОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФактТОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФактТОE", typeof(DataLine.TestGen270624.ФактТО));
                }
            }

            /// <summary>
            /// "ФактТОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФактТОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФактТОL", typeof(DataLine.TestGen270624.ФактТО));
                }
            }
        }
    }
}

